

---loading data trough hive: 
---=================================================
CREATE EXTERNAL TABLE IF NOT EXISTS epidemic_ext(
ID STRING, 
age STRING, 
sex STRING, 
city STRING, 
province STRING, 
country STRING, 
not_wuhan INT, 
latitude STRING, 
longitude STRING, 
geo_resolution STRING, 
date_onset_symptoms STRING, 
date_admission_hospital STRING, 
date_confirmation STRING, 
symptoms STRING, 
lives_in_Wuhan STRING, 
travel_history_dates STRING, 
travel_history_location STRING, 
reported_market_exposure STRING, 
additional_information STRING, 
chronic_disease_binary STRING, 
chronic_disease	STRING, 
source	STRING, 
sequence_available STRING, 
outcome STRING, 
date_death_or_discharge DATE, 
notes_for_discussion STRING, 
location STRING, 
admin3 STRING, 
admin2 STRING, 
admin1 STRING, 
country_new STRING, 
admin_id STRING, 
data_moderator_initials STRING )
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
   "separatorChar" = ",",
   "quoteChar"     = "\""
)
STORED AS TEXTFILE
LOCATION '/tmp/as2'
TBLPROPERTIES("skip.header.line.count"="1");

---temporary table to generate row key 

CREATE temporary TABLE IF NOT EXISTS epidemic_temp(
row_number STRING,
row_key STRING,
disease_code STRING,
ID STRING, 
age STRING, 
sex STRING, 
city STRING, 
province STRING, 
country STRING, 
not_wuhan INT, 
latitude STRING, 
longitude STRING, 
geo_resolution STRING, 
date_onset_symptoms STRING, 
date_admission_hospital STRING, 
date_confirmation STRING, 
symptoms STRING, 
lives_in_Wuhan STRING, 
travel_history_dates STRING, 
travel_history_location STRING, 
reported_market_exposure STRING, 
additional_information STRING, 
chronic_disease_binary STRING, 
chronic_disease	STRING, 
source	STRING, 
sequence_available STRING, 
outcome STRING, 
date_death_or_discharge DATE, 
notes_for_discussion STRING, 
location STRING, 
admin3 STRING, 
admin2 STRING, 
admin1 STRING, 
country_new STRING, 
admin_id STRING, 
data_moderator_initials STRING );

--internal hive table :
CREATE TABLE IF NOT EXISTS epidemic_orc(
row_key STRING,
disease_code STRING,
ID STRING, 
age STRING, 
sex STRING, 
city STRING, 
province STRING, 
country STRING, 
not_wuhan INT, 
latitude STRING, 
longitude STRING, 
geo_resolution STRING, 
date_onset_symptoms STRING, 
date_admission_hospital STRING, 
date_confirmation STRING, 
symptoms STRING, 
lives_in_Wuhan STRING, 
travel_history_dates STRING, 
travel_history_location STRING, 
reported_market_exposure STRING, 
additional_information STRING, 
chronic_disease_binary STRING, 
chronic_disease	STRING, 
source	STRING, 
sequence_available STRING, 
outcome STRING, 
date_death_or_discharge DATE, 
notes_for_discussion STRING, 
location STRING, 
admin3 STRING, 
admin2 STRING, 
admin1 STRING, 
country_new STRING, 
admin_id STRING, 
data_moderator_initials STRING );


---insert from csv to the temporary table
INSERT INTO TABLE epidemic_temp
SELECT
ROW_NUMBER() OVER () AS row_number,
CONCAT('COVID19-',province,'-',country,'-',ID) row_key,
'COVID19' as disease_code,
ID, 
age, 
sex , 
city, 
province , 
country , 
not_wuhan , 
latitude , 
longitude , 
geo_resolution, 
date_onset_symptoms , 
date_admission_hospital , 
date_confirmation , 
symptoms , 
lives_in_Wuhan , 
travel_history_dates , 
travel_history_location , 
reported_market_exposure , 
additional_information , 
chronic_disease_binary , 
chronic_disease	, 
source	, 
sequence_available , 
outcome, 
date_death_or_discharge, 
notes_for_discussion , 
location , 
admin3 , 
admin2 , 
admin1 , 
country_new , 
admin_id , 
data_moderator_initials
FROM epidemic_ext;


INSERT INTO TABLE epidemic_orc
SELECT
CONCAT('COVID19-',province,'-',country,'-',row_number) row_key,
'COVID19' as disease_code,
ID, 
age, 
sex , 
city, 
province , 
country , 
not_wuhan , 
latitude , 
longitude , 
geo_resolution, 
date_onset_symptoms , 
date_admission_hospital , 
date_confirmation , 
symptoms , 
lives_in_Wuhan , 
travel_history_dates , 
travel_history_location , 
reported_market_exposure , 
additional_information , 
chronic_disease_binary , 
chronic_disease	, 
source	, 
sequence_available , 
outcome, 
date_death_or_discharge, 
notes_for_discussion , 
location , 
admin3 , 
admin2 , 
admin1 , 
country_new , 
admin_id , 
data_moderator_initials
FROM epidemic_temp;

--external hbase table 

CREATE EXTERNAL TABLE ext_hbase_epidemic(
  	row_key STRING,
	disease_code STRING,
	ID STRING, 
	age STRING, 
	sex STRING, 
	city STRING, 
	province STRING, 
	country STRING, 
	not_wuhan INT, 
	latitude STRING, 
	longitude STRING, 
	geo_resolution STRING, 
	date_onset_symptoms STRING, 
	date_admission_hospital STRING, 
	date_confirmation STRING, 
	symptoms STRING, 
	lives_in_Wuhan STRING, 
	travel_history_dates STRING, 
	travel_history_location STRING, 
	reported_market_exposure STRING, 
	additional_information STRING, 
	chronic_disease_binary STRING, 
	chronic_disease	STRING, 
	source	STRING, 
	sequence_available STRING, 
	outcome STRING, 
	date_death_or_discharge DATE, 
	notes_for_discussion STRING, 
	location STRING, 
	admin3 STRING, 
	admin2 STRING, 
	admin1 STRING, 
	country_new STRING, 
	admin_id STRING, 
	data_moderator_initials STRING )
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler' 
WITH SERDEPROPERTIES ("hbase.columns.mapping" = 
			   ":key,
			    classification:disease_code,
				meta:ID,
 			    patient:age, 
				patient:sex, 
				location:city,
				location:province, 
				location:country, 
				location:not_wuhan, 
				location:latitude, 
				location:longitude, 
				location:geo_resolution,
				desc:date_onset_symptoms,
				desc:date_admission_hospital,
				desc:date_confirmation,
				desc:symptoms,
				travel_history:lives_in_Wuhan,
				travel_history:dates,
				travel_history:location,
				travel_history:reported_market_exposure,
				desc:additional_information,
				patient:chronic_disease_binary,
				patient:chronic_disease	,
				meta:source	,
				meta:sequence_available,
				desc:outcome,
				desc:date_death_or_discharge,
				desc:notes_for_discussion,
				meta:location,
				meta:admin3, 
				meta:admin2, 
				meta:admin1, 
				meta:country_new, 
				meta:admin_id, 
				meta:data_moderator_initials" ) 
TBLPROPERTIES("hbase.table.name" = "epidemic_tracker","hbase.mapred.output.outputtable" = "epidemic_tracker")

--insert not all the records but for now it is ok 

INSERT INTO TABLE as2.ext_hbase_epidemic SELECT * FROM as2.epidemic_orc;


---

